#!/bin/bash

mkdir -p $BUILD_DIRECTORY
cd $BUILD_DIRECTORY

if [ -n "${RUNTIME_NAME}" ]
then
    NODEJS_NAME_PARAM="-DNODEJS_NAME=${RUNTIME_NAME}"
else
    NODEJS_NAME_PARAM=""
fi

if [ -n "${RUNTIME_URL}" ]
then
    NODEJS_URL_PARAM="-DNODEJS_URL=${RUNTIME_URL}"
else
    NODEJS_URL_PARAM=""
fi

if [ -n "${RUNTIME_VERSION}" ]
then
    NODEJS_VERSION_PARAM="-DNODEJS_VERSION=${RUNTIME_VERSION}"
else
    NODEJS_VERSION_PARAM=""
fi

if [ -n "${ARCHITECTURE}" ]
then
    CMAKE_OSX_ARCHITECTURES_PARAM="-DCMAKE_OSX_ARCHITECTURES=${ARCHITECTURE}"
else
    CMAKE_OSX_ARCHITECTURES_PARAM=""
fi

# Configure
cmake .. \
-DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET} \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_INSTALL_PREFIX=${FULL_DISTRIBUTE_PATH}/node-window-rendering \
${NODEJS_NAME_PARAM} \
${NODEJS_URL_PARAM} \
${NODEJS_VERSION_PARAM} \
${CMAKE_OSX_ARCHITECTURES_PARAM}

# Build and Install
cmake --build . --target install --config RelWithDebInfo
